### ISSUE TITLE
Request: ability to display checkpoint time as a countdown

### ISSUE THREAD

**Issue by trefmanic** [lenku/IngressFace#1]
It would be neat, I think, if a user can select checkpoint time display style. 
Now it displays as a time (CP:  02:00, for example), but a countdown would be also useful to quickly refer this information to agents in other time zones. Something like (CP: -01:34) could allow user to just tell other agents "you have one hour and thirty four minutes until checkpoint".

**Comment by lenku** [comment]
I never thought of that. I will gladly implement it! Development is slow due to how busy I am, but it could very well be up by the end of the weekend if not by the end of today (Friday).

**Comment by lenku** [comment]
The newest version has been published that now includes a countdown timer for the next checkpoint! :dancer: It can be enabled by making sure you have the newest version (2.7) installed and going to the configuration page. Enjoy!
